### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by cgewecke** [nomiclabs/buidler#270]
This is not a bug - just opening and closing in case anyone else is searching this error. 

I often alias `npm test` to a shell script (stolen from Zeppelin) that spins up ganache in the background, executes the test command and shuts ganache down when it's done.  Buidler sometimes launches so fast that ganache isn't ready to accept calls when the tests begin and this error appears. 
```
Error: connect ECONNREFUSED 127.0.0.1:8545
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```
Workaround : add a `sleep 5` between client launch and test command.

**Comment by alcuadrado** [comment]
I experienced this multiple times. It's a little annoying because I'd expect `ganache` not to return until being ready.

Not sure if adding an artificial delay to Buidler is the right thing. I'd rather catch that error and print a helpful message with a hint about this.

Also, we are building a plugin that mimics the OZ script :)

Thanks for the suggestion!

**Comment by alcuadrado** [comment]
Once #332 is merged and a new version published, this errors will be much more descriptive:

```
Error: BDLR109: Cannot connect to the network develop.
Please make sure your node is running, and check your internet connection and networks config
```
