### ISSUE TITLE
[buidler-ethres] Expose more functionality in BRE#ethers

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/buidler#398]
We received feedback about `buidler-ethers` feeling somewhat incomplete. While you can always import `ethers` and use it directly, this feedback is valuable and we should consider adding helpers for common use cases.

If you think something is missing in the plugin, or have ideas about how to improve it, please post it here.

**Comment by gitpusha** [comment]
1
------
 Ideally the buidler-ethers plugin would expose two more async methods:

Both methods would somehow use the `new ethers.Contract(address, abi, providerOrSigner)` under the hood. (see [docs](https://docs.ethers.io/ethers.js/html/api-contract.html#connecting-to-a-contract))

1. getContractWithABIAt(abi, address) 
- this allows for any abi to be passed to the function on the fly (e.g. human readable abi) and does not solely rely on abis being available in the local filesystem.

2. getContractWithNameAt(name, address) 
- this would rely on name resolving to an abi found in the local filesystem, but it would bypass the additional `factory.attach` step required when connecting to deployed instances using the plugin's currently available `getContract(name: string)` method.

Regarding `providers` and `signers` this could be connected by buidler under the hood as it is currently done with `getContract()`. Most importantly, the object connected should be both a provider and a signer (wallet) so that state can both be read and or written to.

2
----
It would be great if the `ethers` buidler env object would also expose `utils` from `ethers.js`.

**Comment by alcuadrado** [comment]
This has been fixed in [`v1.2.0`](https://github.com/nomiclabs/buidler/releases/tag/v1.2.0). Thanks for your suggestions!

Take a look at its new [README](https://github.com/nomiclabs/buidler/tree/master/packages/buidler-ethers#environment-extensions).
