### ISSUE TITLE
sample script fails: ethers is not defined

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/buidler#556]
`node scripts/sample-script.js`
`ReferenceError: ethers is not defined`

**Comment by thegostep** [comment]
`yarn buidler run scripts/sample-script.js` fixes the issue. The CLI seems to have the wrong command

**Comment by viarnes** [comment]
Hey @thegostep, if you run the script through `buidler`, `ethers` is already available on the global scope. When running the script in a standalone fashion with `node`, you have to manually require it. You can do this inside the script with:
```js
const bre = require("@nomiclabs/buidler");
const ethers = bre.ethers;
```
Will add the second line to [the documentation](https://buidler.dev/guides/scripts.html#standalone-scripts-using-buidler-as-a-library) since it's missing. Thanks!

**Comment by viarnes** [comment]
Docs updated. Thanks again @thegostep for reporting.
