### ISSUE TITLE
Buidler doesn't work with monorepos using hoisting

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/buidler#570]
Moving this conversation here from https://github.com/austintgriffith/scaffold-eth/pull/5

> > Hey @forshtat! Patricio from Buidler here.
> > How can I reproduce the problem with workspaces and Buidler plugins?
> > Thanks
> 
> So, for my environment (macOS 10.15.4; yarn 1.16.0; node v13.11.0) in this repo on [cb81fbd](https://github.com/austintgriffith/scaffold-eth/commit/cb81fbd30a09aed7855dd6d25272546cd8d0ab5c) do yarn install. All '@nomiclabs' dependencies go to the root node_modules folder.
> 
> <img alt="Screenshot 2020-05-11 at 14 13 28" width="606" src="https://user-images.githubusercontent.com/40541447/81556192-96a31580-9392-11ea-85c2-5a538ac17518.png">
> 
> Now `cd packages/buidler/` and `yarn add @opengsn/gsn`
> 
> The resulting modules layout is different, as some modules get to a different location:
> 
> <img alt="Screenshot 2020-05-11 at 14 17 24" width="612" src="https://user-images.githubusercontent.com/40541447/81556232-a3276e00-9392-11ea-9530-6b536ca49cfe.png">
> 
> <img alt="Screenshot 2020-05-11 at 14 17 35" width="629" src="https://user-images.githubusercontent.com/40541447/81556241-a6225e80-9392-11ea-98af-c153b59c46cf.png">
> 
> Now trying to run buidler chain:
> 
> ```
> yarn run v1.16.0
> $ cd packages/buidler && npx buidler node --verbose
>   ...
>   ...
>   buidler:core:plugins Loading plugin file /Users/alexf/scaffold-eth/node_modules/@nomiclabs/buidler/builtin-tasks/test +23ms
>   buidler:core:plugins Loading plugin @nomiclabs/buidler-truffle5 +2ms
> Error BDLR800: Plugin @nomiclabs/buidler-truffle5 is not installed.
> Please run: npm install --save-dev @nomiclabs/buidler-truffle5
> 
> For more info go to https://buidler.dev/BDLR800 or run Buidler with --show-stack-traces
> error Command failed with exit code 1.
> ```

**Comment by alcuadrado** [comment]
@0xGabi, is this the same problem that was affecting you?

**Comment by PierrickGT** [comment]
I've forked `scaffold-eth` and found a way to make it work with `yarn workspace`. Here is the commit where you can see the changes I've made: https://github.com/PierrickGT/pooltogether-pod/commit/68b587e0837b49fefbbf530b1b2720b58609767f

I think the main problem is due to the fact that the npm script command is: `cd packages/buidler && npx buidler node --verbose`
By using `npx`, we're using `npm` rather than `yarn` and so I think that's why `npx` can't locate `@nomiclabs/buidler-truffle5`.

By using the command `yarn workspace buidler chain`, we ensure that `yarn` will use the npm script `"chain": "buidler node",` present in the `package.json` of `packages/buidler`, by doing so, we ensure that `yarn` uses the modules that it installed in `packages/buidler`.

**Comment by PaulRBerg** [comment]
FWIW, I'm using Buidler within a yarn workspaces repo and everything works fine, so this should be indeed an issue with your `npx` scripts.

**Comment by 0xGabi** [comment]
Hi @alcuadrado sorry for the late answer. I think it is related but not quite the same as we are using Lerna instead of yarn workspaces.

The comment from @PierrickGT about using `npx` makes me wonder if that might be related. Because we use `npx` in an internal script that start ganache-cli 🤔

**Comment by alcuadrado** [comment]
This issue was fixed and released as 1.4.5.
