### ISSUE TITLE
Deploying from flattened contracts

### ISSUE THREAD

**Issue by thekevinbrown** [nomiclabs/buidler#829]
Hi there,

- We're using [Blockscout](https://blockscout.com)
- Its verification API only supports a single string for the contract source code
- We have the buidler flattener working on our contracts, and it prints out source when we run `buidler flatten`

Currently we're doing:
```typescript
import { ethers } from '@nomiclabs/buidler';

const deploy = async () => {
	// ...
	const Token = await ethers.getContractFactory('Token');
	const token = await Token.deploy();
	await token.deployed();
	console.log(`Token: ${token.address}`);
```

How do we change this script to use the flattened source to build the contract so verification works after deploying the contract?

**Comment by fvictorio** [comment]
I'm not sure what is the best way of doing this. Here's a (not so good) idea:

- Run the flatten task and pipe the result to a new directory, something like `npx buidler flatten > flattened/Flattened.sol`
- Run your deploy script as always, but modify the config at the beggining it so that it uses the `flattened` directory: `config.paths.sources = path.join(config.paths.root, "flattened")`. I think you also need to call the `compile` task after doing this: `await run("compile")`

Not very nice, but it might work.

@alcuadrado might have a better approach.

**Comment by alcuadrado** [comment]
Hey @thekevinbrown,

I don't think you'd need to do that. If blockscout verification only supports that, I bet they ignore the `metadata` of the contracts when verifying.

Have you tried verifying after deploying a normal build?

**Comment by thekevinbrown** [comment]
@alcuadrado Yes, we have, and it appears solc outputs the hash of the source file as part of the bytecode, even if the contents are functionally the same which then fails verification because it doesn't match. (e.g. adding a comment or blank line changes the bytecode produced.)

So we went with @fvictorio's approach. BlockScout is working on updating their verification api so that you can pass multiple files, so that'll help, but in the meantime we're flattening first before we do the build.

Given the move in the community in general away from flattening, I don't know that there's anything to do on Buidler's side at this point, so thanks for the help!

**Comment by alcuadrado** [comment]
Thanks for the detailed answer, @thekevinbrown. I'm glad BlockScout is moving in that direction also.
